### ISSUE TITLE
Couchbase cannot be resolved to a type

### ISSUE THREAD

**Issue by wcomnisky** [arun-gupta/couchbase-javaee#3]
I'm getting the following error in this file#line: [AirlineResource.java#L23](https://github.com/arun-gupta/couchbase-javaee/blob/master/src/main/java/org/couchbase/sample/javaee/AirlineResource.java#L23)

Couchbase cannot be resolved to a type (Java Problem)

It's related to this annotation:
@Couchbase

**Comment by arun-gupta** [comment]
Thanks for the bug, now fixed!

**Comment by wcomnisky** [comment]
:thumbsup:

thanks!
